import type { DemoUser, PolicyDoc, RoleId, ReviewTicket, SecurityEvent } from "./types";

export const ROLE_LABELS: Record<RoleId, string> = {
  employee: "Employee",
  hr_officer: "HR Officer",
  dept_officer: "Department Officer",
  security_officer: "Security Officer",
  admin: "System Administrator",
};

export const DEPARTMENTS = [
  "Personnel",
  "Finance",
  "Revenue",
  "Home Affairs",
  "Information Technology",
];

export const DEMO_USERS: DemoUser[] = [
  {
    employeeId: "EMP102",
    username: "employee.demo",
    password: "demo1234",
    name: "Demo Employee",
    department: "Personnel",
    role: "employee",
    roleLabel: "Junior Assistant",
    clearance: 2,
    deviceTrust: "Trusted",
  },
  {
    employeeId: "HRO214",
    username: "hr.demo",
    password: "demo1234",
    name: "Demo HR Officer",
    department: "Personnel",
    role: "hr_officer",
    roleLabel: "HR Officer",
    clearance: 3,
    deviceTrust: "Trusted",
  },
  {
    employeeId: "DPO330",
    username: "dept.demo",
    password: "demo1234",
    name: "Demo Department Officer",
    department: "Revenue",
    role: "dept_officer",
    roleLabel: "Section Officer",
    clearance: 3,
    deviceTrust: "Managed",
  },
  {
    employeeId: "SEC441",
    username: "security.demo",
    password: "demo1234",
    name: "Demo Security Officer",
    department: "Home Affairs",
    role: "security_officer",
    roleLabel: "Information Security Officer",
    clearance: 4,
    deviceTrust: "Trusted",
  },
  {
    employeeId: "ADM001",
    username: "admin.demo",
    password: "demo1234",
    name: "Demo Administrator",
    department: "Information Technology",
    role: "admin",
    roleLabel: "System Administrator",
    clearance: 5,
    deviceTrust: "Trusted",
  },
];

export const ROLE_SCOPES: Record<
  RoleId,
  { allowed: string[]; restricted: string[]; categories: string[] }
> = {
  employee: {
    allowed: [
      "Leave policies and entitlements",
      "Attendance and working-hour rules",
      "Employee benefits and welfare schemes",
      "General government schemes",
      "Own authorised personal information",
    ],
    restricted: [
      "Confidential investigations",
      "Other employees' private records",
      "Administrative credentials",
      "Security infrastructure information",
    ],
    categories: ["Leave", "Attendance", "Benefits", "LTC", "Employee Welfare", "Government Schemes"],
  },
  hr_officer: {
    allowed: [
      "All employee-facing policies",
      "HR procedures and employee management",
      "Recruitment guidelines",
      "Authorised employee records (aggregate)",
      "Payroll procedure documentation",
    ],
    restricted: [
      "Security infrastructure information",
      "System administration credentials",
      "Active security investigations",
    ],
    categories: [
      "Leave",
      "Attendance",
      "Benefits",
      "LTC",
      "Employee Welfare",
      "Government Schemes",
      "Recruitment",
      "Payroll",
      "Transfers",
    ],
  },
  dept_officer: {
    allowed: [
      "Department-specific policies",
      "Department workflow and approvals",
      "Transfer and posting guidelines",
      "General employee policies",
    ],
    restricted: [
      "Other departments' confidential files",
      "Security infrastructure information",
      "Administrative credentials",
    ],
    categories: [
      "Leave",
      "Attendance",
      "Benefits",
      "LTC",
      "Government Schemes",
      "Transfers",
      "Department Policies",
    ],
  },
  security_officer: {
    allowed: [
      "Security alerts and risk events",
      "Blocked request analytics",
      "Threat and anomaly analytics",
      "Department security policy",
      "General employee policies",
    ],
    restricted: [
      "Plain-text credentials (never stored or disclosed)",
      "Employee medical records",
      "Payroll bank details",
    ],
    categories: [
      "Leave",
      "Attendance",
      "Benefits",
      "Department Policies",
      "Security",
      "Government Schemes",
    ],
  },
  admin: {
    allowed: [
      "User and role management",
      "Knowledge-base and policy version management",
      "Audit logs and security configuration",
      "All non-secret policy documents",
    ],
    restricted: [
      "Plain-text credentials (never stored or disclosed)",
      "Employee medical records",
    ],
    categories: [
      "Leave",
      "Attendance",
      "Benefits",
      "LTC",
      "Employee Welfare",
      "Government Schemes",
      "Recruitment",
      "Payroll",
      "Transfers",
      "Department Policies",
      "Security",
    ],
  },
};

export const POLICIES: PolicyDoc[] = [
  {
    id: "DOC-LEAVE-001",
    title: "Government Leave Policy",
    department: "Personnel",
    category: "Leave",
    classification: "Internal",
    accessRoles: ["employee", "hr_officer", "dept_officer", "security_officer", "admin"],
    minClearance: 1,
    circular: "GOV/HR/2026/007",
    section: "3.1",
    lastUpdated: "2026-07-01",
    expiryDate: null,
    source: "Department of Personnel — Policy Repository (DEMO / FICTIONAL DATA)",
    keywords: [
      "leave",
      "casual",
      "cl",
      "earned",
      "el",
      "sick",
      "medical leave",
      "chutti",
      "raja",
      "avkash",
    ],
    conflict: {
      old: "Casual Leave: 8 days per calendar year (Version 2.0, superseded)",
      current: "Casual Leave: 10 days per calendar year (Version 3.0, current)",
      note: "Two versions matched the query window. Administrator verification pending.",
    },
    versions: [
      {
        version: "3.0",
        effectiveFrom: "2026-07-01",
        effectiveTo: null,
        status: "Current",
        summary: "Casual Leave raised to 10 days; online application mandatory.",
        content:
          "Casual Leave (CL) entitlement is 10 days per calendar year, creditable on 1 January. Applications must be submitted on the departmental e-Leave portal at least 2 working days in advance, except in emergencies where post-facto regularisation within 3 working days is permitted. CL cannot be combined with Earned Leave. Sanctioning authority is the immediate reporting officer.",
      },
      {
        version: "2.0",
        effectiveFrom: "2023-04-01",
        effectiveTo: "2026-06-30",
        status: "Superseded",
        summary: "Casual Leave 8 days; paper application permitted.",
        content:
          "Casual Leave (CL) entitlement is 8 days per calendar year. Applications may be submitted in Form CL-1 to the reporting officer.",
      },
    ],
  },
  {
    id: "DOC-LTC-014",
    title: "Leave Travel Concession (LTC) Guidelines",
    department: "Personnel",
    category: "LTC",
    classification: "Internal",
    accessRoles: ["employee", "hr_officer", "dept_officer", "security_officer", "admin"],
    minClearance: 1,
    circular: "GOV/HR/2026/014",
    section: "4.2",
    lastUpdated: "2026-07-04",
    expiryDate: null,
    source: "Department of Personnel — LTC Cell (DEMO / FICTIONAL DATA)",
    keywords: ["ltc", "travel", "concession", "home town", "block year", "yatra"],
    versions: [
      {
        version: "4.0",
        effectiveFrom: "2026-07-04",
        effectiveTo: null,
        status: "Current",
        summary: "LTC eligibility after 1 year of continuous service; 4-year block.",
        content:
          "An employee who has completed one year of continuous service is eligible for LTC. Entitlement is one Home Town LTC in each two-year block and one All India LTC in each four-year block. Advance may be drawn up to 90% of the estimated fare, and the claim must be settled within 30 days of completion of the journey. Air travel is admissible only for entitled grades as per the fare table in Annexure II.",
      },
      {
        version: "3.0",
        effectiveFrom: "2023-01-01",
        effectiveTo: "2026-07-03",
        status: "Superseded",
        summary: "LTC eligibility after 2 years of service; advance limited to 80%.",
        content:
          "An employee who has completed two years of continuous service is eligible for LTC. Advance may be drawn up to 80% of estimated fare. Claim settlement window is 45 days.",
      },
    ],
  },
  {
    id: "DOC-MAT-021",
    title: "Maternity and Child Care Leave Policy",
    department: "Personnel",
    category: "Leave",
    classification: "Internal",
    accessRoles: ["employee", "hr_officer", "dept_officer", "security_officer", "admin"],
    minClearance: 1,
    circular: "GOV/HR/2025/021",
    section: "2.4",
    lastUpdated: "2025-11-18",
    expiryDate: null,
    source: "Department of Personnel — Welfare Section (DEMO / FICTIONAL DATA)",
    keywords: [
      "maternity",
      "child care",
      "pregnancy",
      "matritva",
      "documents",
      "paternity",
      "prasuti",
    ],
    versions: [
      {
        version: "2.0",
        effectiveFrom: "2025-11-18",
        effectiveTo: null,
        status: "Current",
        summary: "180 days maternity leave; documents and application route.",
        content:
          "Maternity Leave of 180 days is admissible to a female government servant with fewer than two surviving children. Required documents: (a) application in Form ML-1, (b) medical certificate from a registered practitioner indicating expected date of delivery, (c) service book reference, (d) declaration of number of surviving children. Child Care Leave of up to 730 days over the entire service is admissible subject to sanction. Paternity Leave of 15 days is admissible within 6 months of the date of delivery.",
      },
    ],
  },
  {
    id: "DOC-TRF-009",
    title: "Employee Transfer and Posting Policy",
    department: "Personnel",
    category: "Transfers",
    classification: "Internal",
    accessRoles: ["employee", "hr_officer", "dept_officer", "admin"],
    minClearance: 2,
    circular: "GOV/HR/2026/009",
    section: "5.1",
    lastUpdated: "2026-03-12",
    expiryDate: null,
    source: "Department of Personnel — Establishment Branch (DEMO / FICTIONAL DATA)",
    keywords: ["transfer", "posting", "relocation", "documents", "tabadla", "badli"],
    versions: [
      {
        version: "2.1",
        effectiveFrom: "2026-03-12",
        effectiveTo: null,
        status: "Current",
        summary: "Transfer request documents and minimum tenure.",
        content:
          "A transfer request requires: (a) Form TR-1 duly forwarded by the reporting officer, (b) a No-Objection Certificate from the current office, (c) the last two Annual Performance Appraisal Reports, (d) a vigilance clearance certificate, and (e) supporting documents for compassionate grounds, where claimed. Minimum tenure at a station is normally 3 years. Joining time of up to 8 days is admissible for inter-station transfers.",
      },
    ],
  },
  {
    id: "DOC-ATT-004",
    title: "Attendance and Working Hours Policy",
    department: "Personnel",
    category: "Attendance",
    classification: "Public",
    accessRoles: ["employee", "hr_officer", "dept_officer", "security_officer", "admin"],
    minClearance: 1,
    circular: "GOV/ADM/2026/004",
    section: "1.2",
    lastUpdated: "2026-01-09",
    expiryDate: null,
    source: "Administration Wing (DEMO / FICTIONAL DATA)",
    keywords: ["attendance", "biometric", "working hours", "late", "hajri", "timing"],
    versions: [
      {
        version: "1.3",
        effectiveFrom: "2026-01-09",
        effectiveTo: null,
        status: "Current",
        summary: "Office hours 09:30–18:00; biometric marking mandatory.",
        content:
          "Office hours are 09:30 to 18:00 with a 30-minute lunch interval. Biometric attendance is mandatory at entry and exit. A grace period of 15 minutes is permitted on not more than two occasions in a month; further late attendance is adjusted against Casual Leave. Work-from-home may be sanctioned up to 4 days a month by the Head of Office.",
      },
    ],
  },
  {
    id: "DOC-PAY-031",
    title: "Payroll Processing Procedure",
    department: "Finance",
    category: "Payroll",
    classification: "Restricted",
    accessRoles: ["hr_officer", "admin"],
    minClearance: 3,
    circular: "GOV/FIN/2026/031",
    section: "6.3",
    lastUpdated: "2026-05-20",
    expiryDate: null,
    source: "Finance Department — Pay Cell (DEMO / FICTIONAL DATA)",
    keywords: ["payroll", "salary", "pay slip", "deduction", "vetan", "pagar"],
    versions: [
      {
        version: "1.2",
        effectiveFrom: "2026-05-20",
        effectiveTo: null,
        status: "Current",
        summary: "Monthly payroll cycle, cut-off dates and deduction handling.",
        content:
          "Payroll input cut-off is the 18th of each month. Pay bills are passed by the 25th and credited on the last working day. Statutory deductions are applied in the order: NPS/GPF, income tax, professional tax, recoveries. Pay slips are published on the employee self-service portal; bank details are never shared over chat or email.",
      },
    ],
  },
  {
    id: "DOC-REC-017",
    title: "Recruitment and Selection Guidelines",
    department: "Personnel",
    category: "Recruitment",
    classification: "Internal",
    accessRoles: ["hr_officer", "dept_officer", "admin"],
    minClearance: 3,
    circular: "GOV/HR/2026/017",
    section: "2.2",
    lastUpdated: "2026-02-14",
    expiryDate: null,
    source: "Recruitment Board (DEMO / FICTIONAL DATA)",
    keywords: ["recruitment", "selection", "vacancy", "interview", "bharti"],
    versions: [
      {
        version: "3.1",
        effectiveFrom: "2026-02-14",
        effectiveTo: null,
        status: "Current",
        summary: "Vacancy notification, screening and interview panel composition.",
        content:
          "Vacancies are notified for a minimum of 21 days. Screening is done against essential qualifications only. The interview panel comprises a chairperson, a subject expert and a representative of the reserved-category cell. Reservation rosters are maintained as per applicable orders. Selection panels remain valid for one year.",
      },
    ],
  },
  {
    id: "DOC-WEL-025",
    title: "Employee Welfare Scheme Handbook",
    department: "Personnel",
    category: "Employee Welfare",
    classification: "Public",
    accessRoles: ["employee", "hr_officer", "dept_officer", "security_officer", "admin"],
    minClearance: 1,
    circular: "GOV/WEL/2026/025",
    section: "3.5",
    lastUpdated: "2026-04-02",
    expiryDate: null,
    source: "Welfare Directorate (DEMO / FICTIONAL DATA)",
    keywords: ["welfare", "benefit", "medical", "insurance", "scholarship", "yojana", "scheme"],
    versions: [
      {
        version: "2.0",
        effectiveFrom: "2026-04-02",
        effectiveTo: null,
        status: "Current",
        summary: "Medical reimbursement, group insurance and children's scholarships.",
        content:
          "Employees are covered under the group medical scheme with cashless treatment at empanelled hospitals. Children's education allowance is admissible for two children on production of a bona fide certificate. Interest-bearing advances are available for house building and computer purchase. Applications are made through the welfare module of the HR portal.",
      },
    ],
  },
  {
    id: "DOC-SEC-002",
    title: "Department Information Security Policy",
    department: "Home Affairs",
    category: "Security",
    classification: "Confidential",
    accessRoles: ["security_officer", "admin"],
    minClearance: 4,
    circular: "GOV/SEC/2026/002",
    section: "7.1",
    lastUpdated: "2026-06-11",
    expiryDate: null,
    source: "Information Security Wing (DEMO / FICTIONAL DATA)",
    keywords: ["security", "incident", "vpn", "access control", "threat", "investigation"],
    versions: [
      {
        version: "5.0",
        effectiveFrom: "2026-06-11",
        effectiveTo: null,
        status: "Current",
        summary: "Incident classification, reporting timelines and access reviews.",
        content:
          "Security incidents are classified as P1 to P4. P1 incidents must be reported to the departmental CISO within 30 minutes. Quarterly access reviews are mandatory for all privileged accounts. Credentials are never transmitted over chat, email or AI assistants. Any suspected credential exposure requires immediate rotation and an entry in the incident register.",
      },
    ],
  },
  {
    id: "DOC-DEP-040",
    title: "Departmental Workflow and Approval Matrix",
    department: "Revenue",
    category: "Department Policies",
    classification: "Restricted",
    accessRoles: ["dept_officer", "hr_officer", "admin"],
    minClearance: 3,
    circular: "GOV/REV/2026/040",
    section: "2.7",
    lastUpdated: "2026-05-05",
    expiryDate: null,
    source: "Revenue Department (DEMO / FICTIONAL DATA)",
    keywords: ["workflow", "approval", "file", "noting", "department", "matrix"],
    versions: [
      {
        version: "1.1",
        effectiveFrom: "2026-05-05",
        effectiveTo: null,
        status: "Current",
        summary: "File movement levels and financial approval limits.",
        content:
          "Files move through Assistant, Section Officer, Under Secretary and Deputy Secretary levels. Financial approvals up to Rs 50,000 rest with the Section Officer, up to Rs 5,00,000 with the Under Secretary and beyond that with the Head of Department. e-Office noting is mandatory; parallel physical files are not permitted.",
      },
    ],
  },
];

export const SEED_EVENTS: SecurityEvent[] = [
  {
    id: "SEV-1001",
    timestamp: "2026-08-16T07:12:00.000Z",
    userId: "EMP102",
    department: "Personnel",
    action: "Credential Detection",
    riskLevel: "CRITICAL",
    result: "BLOCKED",
    reason: "Credential pattern detected in query — value not stored",
  },
  {
    id: "SEV-1002",
    timestamp: "2026-08-16T06:48:00.000Z",
    userId: "DPO330",
    department: "Revenue",
    action: "PII Redaction",
    riskLevel: "MEDIUM",
    result: "REDACTED",
    reason: "Aadhaar-like identifier redacted before model call",
  },
  {
    id: "SEV-1003",
    timestamp: "2026-08-16T06:20:00.000Z",
    userId: "EMP102",
    department: "Personnel",
    action: "RBAC Authorisation",
    riskLevel: "HIGH",
    result: "DENIED",
    reason: "Requested classification exceeds clearance level",
  },
  {
    id: "SEV-1004",
    timestamp: "2026-08-15T13:42:00.000Z",
    userId: "HRO214",
    department: "Personnel",
    action: "Policy Conflict",
    riskLevel: "MEDIUM",
    result: "ESCALATED",
    reason: "Conflicting policy versions surfaced for Casual Leave",
  },
  {
    id: "SEV-1005",
    timestamp: "2026-08-15T11:05:00.000Z",
    userId: "EMP102",
    department: "Personnel",
    action: "Knowledge Retrieval",
    riskLevel: "LOW",
    result: "ALLOWED",
    reason: "Authorised policy answer delivered with citation",
  },
];

export const SEED_TICKETS: ReviewTicket[] = [
  {
    id: "REV-2041",
    employeeId: "EMP102",
    employeeName: "Demo Employee",
    department: "Personnel",
    question: "Am I eligible for LTC in the current block year?",
    riskLevel: "LOW",
    aiAnswer:
      "Eligibility depends on completion of one year of continuous service and the applicable block year.",
    sources: ["GOV/HR/2026/014 §4.2"],
    createdAt: "2026-08-15T09:30:00.000Z",
    status: "Under Review",
  },
  {
    id: "REV-2042",
    employeeId: "DPO330",
    employeeName: "Demo Department Officer",
    department: "Revenue",
    question: "Which approval level applies to a Rs 6,00,000 procurement?",
    riskLevel: "MEDIUM",
    aiAnswer: "Approvals beyond Rs 5,00,000 rest with the Head of Department.",
    sources: ["GOV/REV/2026/040 §2.7"],
    createdAt: "2026-08-14T12:10:00.000Z",
    status: "Resolved",
    officerNote: "Confirmed. HoD approval required with concurrence of Finance.",
  },
];

export function findUser(identifier: string): DemoUser | undefined {
  const key = identifier.trim().toLowerCase();
  return DEMO_USERS.find(
    (u) => u.username.toLowerCase() === key || u.employeeId.toLowerCase() === key,
  );
}
